name: Update Helm Chart from Develop Image Tag

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Fetch latest image tag from develop branch of Helm Charts Repo to remove manual interventions.
  # We are fetching the tag from develop branch since our app has been tested in develop and now we can deploy same image to
  # Production servers and as soon as develop branch is merged into main, our helm repo will also be synced with same tags.
  fetch-develop-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.get_tag.outputs.image_tag }}
    steps:
      - name: Checkout app repository (develop branch)
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.ARGO_REPO_NAME }}
          ref: develop
          token: ${{ secrets.REPO_TOKEN }}

      - name: Get latest image tag from develop
        id: get_tag
        run: |
          IMAGE_TAG=$(grep 'tag:' helm-chart/values-gradle-dev.yaml | awk '{print $2}')
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Fetched image tag from develop: $IMAGE_TAG"

  # Job 2: Update Helm chart in main branch of Helm Chart's repo
  update-helm:
    runs-on: ubuntu-latest
    needs: fetch-develop-tag
    env:
      IMAGE_REPO_NAME: ${{ secrets.IMAGE_REPO_NAME }}
      IMAGE_TAG: ${{ needs.fetch-develop-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Argo repo main branch
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.ARGO_REPO_NAME }}
          ref: main
          token: ${{ secrets.REPO_TOKEN }}

      - name: Update Helm chart Image Tag in dev-file and prod-file so that we have dev and prod in sync.
        run: |
          echo "Updating Helm chart in Argo repo..."
          sed -i "s|^\s*repository: .*|  repository: $IMAGE_REPO_NAME|" helm-chart/values-gradle.yaml
          sed -i "s|^\s*tag: .*|  tag: $IMAGE_TAG|" helm-chart/values-gradle.yaml
          sed -i "s|^\s*repository: .*|  repository: $IMAGE_REPO_NAME|" helm-chart/values-gradle-dev.yaml
          sed -i "s|^\s*tag: .*|  tag: $IMAGE_TAG|" helm-chart/values-gradle-dev.yaml
          echo "Updated Helm chart:"
          cat helm-chart/values-gradle.yaml

      - name: Commit and push changes to main
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "Update deployment image to $IMAGE_TAG from develop"
          add: 'helm-chart/values-gradle.yaml helm-chart/values-gradle-dev.yaml'
          new_branch: main
